spring.application.name=merchant
server.port=8081

spring.cloud.aws.dynamodb.endpoint=http://localhost:8000
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=ylyf6j
spring.cloud.aws.credentials.secret-key=30u5bn
